volumes:
  pg_flask:

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - pg_flask:/var/lib/postgresql/data
    networks:
      - app-network

  order-service:
    build: './order-service'
    container_name: order_service
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./order-service:/app

  api-gateway:
    build: './api-gateway'
    container_name: api-gateway
    ports:
      - "80:80"
    depends_on:
      - order-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
