volumes:
  tcc_pg_data:

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - tcc_pg_data:/var/lib/postgresql/data
    networks:
      - tcc-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: tcc-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - tcc-network

  order-service:
    build: './order-service'
    container_name: order_service
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    expose:
      - "8000"
    depends_on:
      - db
      - rabbitmq
    networks:
      - tcc-network
    volumes:
      - ./order-service:/app

  api-gateway:
    build: './api-gateway'
    container_name: api-gateway
    ports:
      - "80:80"
    depends_on:
      - order-service
    networks:
      - tcc-network
  
  payment-service:
    build: './payment-service'
    container_name: payment_service
    restart: always
    depends_on:
      - rabbitmq
      - order-service
    networks:
      - tcc-network

networks:
  tcc-network:
    driver: bridge
